import type { Tag } from "./CategoryTagModal";

export const allTags: Tag[] = [
  // 프론트엔드
  { label: "HTML", category: "프론트엔드" },
  { label: "CSS", category: "프론트엔드" },
  { label: "JS", category: "프론트엔드" },
  { label: "TS", category: "프론트엔드" },
  { label: "React", category: "프론트엔드" },
  { label: "Vue", category: "프론트엔드" },
  { label: "Angular", category: "프론트엔드" },
  { label: "Next.js", category: "프론트엔드" },
  { label: "Redux", category: "프론트엔드" },
  { label: "Tailwind CSS", category: "프론트엔드" },
  { label: "jQuery", category: "프론트엔드" },
  { label: "vite", category: "프론트엔드" },
  { label: "npm", category: "프론트엔드" },
  { label: "yarn", category: "프론트엔드" },
  { label: "UI", category: "프론트엔드" },
  { label: "props", category: "프론트엔드" },
  { label: "Zustand", category: "프론트엔드" },
  { label: "webPack", category: "프론트엔드" },
  { label: "ESLint", category: "프론트엔드" },
  { label: "Axios", category: "프론트엔드" },
  { label: "Fetch", category: "프론트엔드" },
  { label: "API", category: "프론트엔드" },
  { label: "HTTP", category: "프론트엔드" },
  { label: "Error Boundary", category: "프론트엔드" },

  // 백엔드
  { label: "Java", category: "백엔드" },
  { label: "Kotlin", category: "백엔드" },
  { label: "Python", category: "백엔드" },
  { label: "Node.js", category: "백엔드" },
  { label: "C#", category: "백엔드" },
  { label: "PHP", category: "백엔드" },
  { label: "Ruby", category: "백엔드" },
  { label: "Go", category: "백엔드" },
  { label: "Scala", category: "백엔드" },
  { label: "Rust", category: "백엔드" },
  { label: "Spring Boot", category: "백엔드" },
  { label: "Django", category: "백엔드" },
  { label: "Flask", category: "백엔드" },
  { label: "Express.js", category: "백엔드" },
  { label: "NestJS", category: "백엔드" },
  { label: "Laravel", category: "백엔드" },
  { label: "ASP.NET Core", category: "백엔드" },
  { label: "Ruby on Rails", category: "백엔드" },

  // 데이터베이스
  { label: "SQL", category: "데이터베이스" },
  { label: "NoSQL", category: "데이터베이스" },
  { label: "MySQL", category: "데이터베이스" },
  { label: "PostgreSQL", category: "데이터베이스" },
  { label: "MongoDB", category: "데이터베이스" },
  { label: "데이터정규화", category: "데이터베이스" },
  { label: "ERD", category: "데이터베이스" },
  { label: "트랜잭션", category: "데이터베이스" },
  { label: "Key", category: "데이터베이스" },
  { label: "Index", category: "데이터베이스" },
  { label: "JOIN", category: "데이터베이스" },
  { label: "스키마", category: "데이터베이스" },
  { label: "ORM", category: "데이터베이스" },
  { label: "Lock", category: "데이터베이스" },
  { label: "Deadlock", category: "데이터베이스" },
  { label: "Slow Query", category: "데이터베이스" },
  { label: "Connection Timeout", category: "데이터베이스" },
  { label: "Query Optimization", category: "데이터베이스" },
  { label: "백업•복원", category: "데이터베이스" },

  // 데브옵스
  { label: "Linux", category: "데브옵스" },
  { label: "Go", category: "데브옵스" },
  { label: "Python", category: "데브옵스" },
  { label: "Docker", category: "데브옵스" },
  { label: "Kubernetes", category: "데브옵스" },
  { label: "Terraform", category: "데브옵스" },
  { label: "Ansible", category: "데브옵스" },
  { label: "Jenkins", category: "데브옵스" },
  { label: "CI/CD", category: "데브옵스" },
  { label: "Github Actions", category: "데브옵스" },
  { label: "AWS", category: "데브옵스" },
  { label: "GCP", category: "데브옵스" },
  { label: "Azure", category: "데브옵스" },
  { label: "Prometheus", category: "데브옵스" },
  { label: "Grafana", category: "데브옵스" },
  { label: "Helm", category: "데브옵스" },
  { label: "Nginx", category: "데브옵스" },
  { label: "ArgoCD", category: "데브옵스" },
  { label: "Bash", category: "데브옵스" },

  // 기타
  { label: "Git", category: "기타" },
  { label: "GitHub", category: "기타" },
  { label: "Postman", category: "기타" },
  { label: "Swagger", category: "기타" },
  { label: "OpenAPI", category: "기타" },
  { label: "JWT", category: "기타" },
  { label: "OAuth", category: "기타" },
  { label: "Helmet", category: "기타" },
  { label: "Jest", category: "기타" },
  { label: "Vitest", category: "기타" },
  { label: "TestCode", category: "기타" },
  { label: "WebSocket", category: "기타" },
  { label: "SSE", category: "기타" },
  { label: "Session", category: "기타" },
  { label: "2FA", category: "기타" },
  { label: "LightHouse", category: "기타" },
  { label: "BundleAnalyzer", category: "기타" },
];
