import type { Tag } from "@/pages/TempWrite/CategoryTagModal";

export const allTags: Tag[] = [
  // 프론트엔드
  { label: "HTML", category: "프론트엔드" },
  { label: "CSS", category: "프론트엔드" },
  { label: "JavaScript", category: "프론트엔드" },
  { label: "TypeScript", category: "프론트엔드" },
  { label: "React", category: "프론트엔드" },
  { label: "Vue.js", category: "프론트엔드" },
  { label: "Angular", category: "프론트엔드" },
  { label: "Next.js", category: "프론트엔드" },
  { label: "Redux", category: "프론트엔드" },
  { label: "Zustand", category: "프론트엔드" },
  { label: "Tailwind CSS", category: "프론트엔드" },
  { label: "Bootstrap", category: "프론트엔드" },
  { label: "Material-UI", category: "프론트엔드" },
  { label: "jQuery", category: "프론트엔드" },
  { label: "Axios", category: "프론트엔드" },
  { label: "Fetch", category: "프론트엔드" },
  { label: "Vite", category: "프론트엔드" },
  { label: "Webpack", category: "프론트엔드" },
  { label: "ESLint", category: "프론트엔드" },
  { label: "npm", category: "프론트엔드" },
  { label: "yarn", category: "프론트엔드" },
  { label: "Error Boundary", category: "프론트엔드" },
  { label: "Props", category: "프론트엔드" },
  { label: "Component", category: "프론트엔드" },
  { label: "HTTP", category: "프론트엔드" },

  // 백엔드
  { label: "Java", category: "백엔드" },
  { label: "Kotlin", category: "백엔드" },
  { label: "Python", category: "백엔드" },
  { label: "Node.js", category: "백엔드" },
  { label: "Go", category: "백엔드" },
  { label: "Rust", category: "백엔드" },
  { label: "Scala", category: "백엔드" },
  { label: "Ruby", category: "백엔드" },
  { label: "PHP", category: "백엔드" },
  { label: "C#", category: "백엔드" },
  { label: "ASP.NET Core", category: "백엔드" },
  { label: "Spring Boot", category: "백엔드" },
  { label: "Django", category: "백엔드" },
  { label: "Flask", category: "백엔드" },
  { label: "Express.js", category: "백엔드" },
  { label: "NestJS", category: "백엔드" },
  { label: "Laravel", category: "백엔드" },
  { label: "Ruby on Rails", category: "백엔드" },
  { label: "REST API", category: "백엔드" },
  { label: "GraphQL", category: "백엔드" },
  { label: "Session", category: "백엔드" },
  { label: "JWT", category: "백엔드" },
  { label: "OAuth", category: "백엔드" },
  { label: "WebSocket", category: "백엔드" },
  { label: "SSE", category: "백엔드" },
  { label: "Helmet", category: "백엔드" },
  { label: "Postman", category: "백엔드" },
  { label: "Swagger", category: "백엔드" },
  { label: "OpenAPI", category: "백엔드" },

  // 데이터베이스
  { label: "SQL", category: "데이터베이스" },
  { label: "NoSQL", category: "데이터베이스" },
  { label: "MySQL", category: "데이터베이스" },
  { label: "PostgreSQL", category: "데이터베이스" },
  { label: "MongoDB", category: "데이터베이스" },
  { label: "Redis", category: "데이터베이스" },
  { label: "MariaDB", category: "데이터베이스" },
  { label: "데이터 정규화", category: "데이터베이스" },
  { label: "ERD", category: "데이터베이스" },
  { label: "트랜잭션", category: "데이터베이스" },
  { label: "Key", category: "데이터베이스" },
  { label: "Index", category: "데이터베이스" },
  { label: "JOIN", category: "데이터베이스" },
  { label: "스키마", category: "데이터베이스" },
  { label: "ORM", category: "데이터베이스" },
  { label: "Lock", category: "데이터베이스" },
  { label: "Slow Query", category: "데이터베이스" },
  { label: "Connection Timeout", category: "데이터베이스" },
  { label: "Query Optimization", category: "데이터베이스" },

  // 데브옵스
  { label: "Linux", category: "데브옵스" },
  { label: "Bash", category: "데브옵스" },
  { label: "Docker", category: "데브옵스" },
  { label: "Kubernetes", category: "데브옵스" },
  { label: "Terraform", category: "데브옵스" },
  { label: "Ansible", category: "데브옵스" },
  { label: "Jenkins", category: "데브옵스" },
  { label: "GitHub Actions", category: "데브옵스" },
  { label: "ArgoCD", category: "데브옵스" },
  { label: "Helm", category: "데브옵스" },
  { label: "Prometheus", category: "데브옵스" },
  { label: "Grafana", category: "데브옵스" },
  { label: "CI/CD 파이프라인", category: "데브옵스" },
  { label: "모니터링/로깅", category: "데브옵스" },
  { label: "서버 상태 관리", category: "데브옵스" },
  { label: "인프라 코드화", category: "데브옵스" },

  // 인프라
  { label: "AWS", category: "인프라" },
  { label: "GCP", category: "인프라" },
  { label: "Azure", category: "인프라" },
  { label: "Vercel", category: "인프라" },
  { label: "Netlify", category: "인프라" },
  { label: "가상화", category: "인프라" },
  { label: "오케스트레이션", category: "인프라" },
  { label: "리버스 프록시", category: "인프라" },
  { label: "로드 밸런싱", category: "인프라" },
  { label: "CDN", category: "인프라" },
  { label: "SSL/TLS/HTTPS", category: "인프라" },
  { label: "DNS", category: "인프라" },
  { label: "VPC", category: "인프라" },
  { label: "방화벽", category: "인프라" },
  { label: "WAF", category: "인프라" },
  { label: "서버리스", category: "인프라" },
  { label: "백업 및 복구 전략", category: "인프라" },

  // 기타
  { label: "Git", category: "기타" },
  { label: "GitHub", category: "기타" },
  { label: "GitLab", category: "기타" },
  { label: "Bitbucket", category: "기타" },
  { label: "JWT", category: "기타" },
  { label: "OAuth", category: "기타" },
  { label: "2FA", category: "기타" },
  { label: "Postman", category: "기타" },
  { label: "Swagger", category: "기타" },
  { label: "OpenAPI", category: "기타" },
  { label: "Jest", category: "기타" },
  { label: "Vitest", category: "기타" },
  { label: "TestCode", category: "기타" },
  { label: "Lighthouse", category: "기타" },
  { label: "BundleAnalyzer", category: "기타" },
];
